### ISSUE TITLE
Fails to build with Shapely 2.0

### ISSUE THREAD

**Issue by sebastic** [mapproxy/mapproxy#611]
## Context
The build fails due to test failures:
```
mapproxy/test/unit/test_geom.py:169: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

datasource = '/tmp/tmp9u365ato'

    def load_geojson(datasource):
        with open(datasource) as f:
            geojson = json.load(f)
            t = geojson.get('type')
            if not t:
                raise CoverageReadError("not a GeoJSON")
            geometries = []
            if t == 'FeatureCollection':
                for f in geojson.get('features'):
                    geom = f.get('geometry')
                    if geom:
                        geometries.append(geom)
            elif t == 'Feature':
                if 'geometry' in geojson:
                    geometries.append(geojson['geometry'])
            elif t in ('Polygon', 'MultiPolygon'):
                geometries.append(geojson)
            else:
                log_config.warning('skipping feature of type %s from %s: not a Polygon/MultiPolygon',
                            t, datasource)
    
        polygons = []
        for geom in geometries:
>           geom = shapely.geometry.asShape(geom)
E           AttributeError: module 'shapely.geometry' has no attribute 'asShape'

mapproxy/util/geom.py:147: AttributeError
_ TestGeoJSONLoading.test_geojson[{"type": "MultiPolygon", "coordinates": [[[[0, 0], [10, 0], [10, 10], [0, 0]]], [[[20, 0], [30, 0], [20, 10], [20, 0]]]]}-geometry1] _

self = <mapproxy.test.unit.test_geom.TestGeoJSONLoading object at 0x7fc1d8d7af80>
geojson = '{"type": "MultiPolygon", "coordinates": [[[[0, 0], [10, 0], [10, 10], [0, 0]]], [[[20, 0], [30, 0], [20, 10], [20, 0]]]]}'
geometry = <MULTIPOLYGON (((0 0, 10 0, 10 10, 0 0)), ((20 0, 30 0, 20 10, 20 0)))>

    @pytest.mark.parametrize('geojson,geometry', [
        [ '''{"type": "Polygon", "coordinates": [[[0, 0], [10, 0], [10, 10], [0, 0]]]}''',
            shapely.geometry.Polygon([[0, 0], [10, 0], [10, 10], [0, 0]]), ],
        [ '''{"type": "MultiPolygon", "coordinates": [[[[0, 0], [10, 0], [10, 10], [0, 0]]], [[[20, 0], [30, 0], [20, 10], [20, 0]]]]}''',
            shapely.geometry.Polygon([[0, 0], [10, 0], [10, 10], [0, 0]]).union(shapely.geometry.Polygon([[20, 0], [30, 0], [20, 10], [20, 0]])), ],
        [ '''{"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[0, 0], [10, 0], [10, 10], [0, 0]]]}}''',
            shapely.geometry.Polygon([[0, 0], [10, 0], [10, 10], [0, 0]]), ],
        [ '''{"type": "FeatureCollection", "features": [{"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[0, 0], [10, 0], [10, 10], [0, 0]]]}}]}''',
            shapely.geometry.Polygon([[0, 0], [10, 0], [10, 10], [0, 0]]), ],
    ])
    def test_geojson(self, geojson, geometry):
        with TempFile() as fname:
            with open(fname, 'w') as f:
                f.write(geojson)
>           polygon = load_geojson(fname)
```
```
____________________ TestTransform.test_multipolygon_transf ____________________

self = <mapproxy.test.unit.test_geom.TestTransform object at 0x7fc1d8d7a860>

    def test_multipolygon_transf(self):
        p1 = shapely.geometry.Polygon([(0, 0), (10, 0), (10, 10), (0, 10)])
        p2 = shapely.geometry.Polygon([(20, 20), (30, 20), (30, 30), (20, 30)])
        mp1 = shapely.geometry.MultiPolygon([p1, p2])
    
>       mp2 = transform_geometry(SRS(4326), SRS(900913), mp1)

mapproxy/test/unit/test_geom.py:191: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
mapproxy/util/geom.py:222: in transform_geometry
    result = transform_multipolygon(transf, geometry)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

transf = functools.partial(<function transform_xy at 0x7fc1da670d30>, SRS('EPSG:4326'), SRS('EPSG:900913'))
multipolygon = <MULTIPOLYGON (((0 0, 10 0, 10 10, 0 10, 0 0)), ((20 20, 30 20, 30 30, 20 30...>

    def transform_multipolygon(transf, multipolygon):
        transformed_polygons = []
>       for polygon in multipolygon:
E       TypeError: 'MultiPolygon' object is not iterable

mapproxy/util/geom.py:237: TypeError
```

## Expected Behavior
No test failures

## Actual Behavior
Test failures.

## Steps to Reproduce
1. Run mapproxy test suite with shapely >= 2.0

## Context
Evaluating the impact of moving the python-shapely Debian package from experimental to unstable before the freeze in February.

## Your Environment

* Version used: 1.15.1
* Environment name and version: Python 3.10.8 with Shapely 2.0rc2
* Server type and version: N/A
* Operating System and version: Debian unstable with python3-shapely from experimental

**Comment by sebastic** [comment]
Shapely 2.0 has been released:

 https://github.com/shapely/shapely/releases/tag/2.0.0

**Comment by weskamm** [comment]
As shapely is not used in version 2.0, i dont see the issue here:
https://github.com/mapproxy/mapproxy/blob/master/requirements-tests.txt#L7

For me it looks like that we have a fixed version 1.7.

If you think something is not working with an unmodified requirements.txt, feel free to reopen this.

**Comment by sebastic** [comment]
The Debian package cannot use the pinned versions.

> If you think something is not working with an unmodified requirements.txt, feel free to reopen this.

I can only comment on this issue, not reopen it.

**Comment by weskamm** [comment]
i see, i will reopen this and mark as bug, thanks for the report!

**Comment by weskamm** [comment]
@olt Could you point me to the direction where those debian build scripts are triggered? i would like to integrate that into github actions if possible to have those things in one place
