### PR TITLE
Bump to Shapely 2.0.1

### LINKED ISSUE #611: Fails to build with Shapely 2.0
## Context
The build fails due to test failures:
```
mapproxy/test/unit/test_geom.py:169: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

datasource = '/tmp/tmp9u365ato'

    def load_geojson(datasource):
        with open(datasource) as f:
            geojson = json.load(f)
            t = geojson.get('type')
            if not t:
                raise CoverageReadError("not a GeoJSON")
            geometries = []
            if t == 'FeatureCollection':
                for f in geojson.get('features'):
                    geom = f.get('geometry')
                    if geom:
                        geometries.append(geom)
            elif t == 'Feature':
                if 'geometry' in geojson:
                    geometries.append(geojson['geometry'])
            elif t in ('Polygon', 'MultiPolygon'):
                geometries.append(geojson)
            else:
                log_config.warning('skipping feature of type %s from %s: not a Polygon/MultiPolygon',
                            t, datasource)
    
        polygons = []
        for geom in geometries:
>           geom = shapely.geometry.asShape(geom)
E           AttributeError: module 'shapely.geometry' has no attribute 'asShape'

mapproxy/util/geom.py:147: AttributeError
_ TestGeoJSONLoading.test_geojson[{"type": "MultiPolygon", "coordinates": [[[[0, 0], [10, 0], [10, 10], [0, 0]]], [[[20, 0], [30, 0], [20, 10], [20, 0]]]]}-geometry1] _

self = <mapproxy.test.unit.test_geom.TestGeoJSONLoading object at 0x7fc1d8d7af80>
geojson = '{"type": "MultiPolygon", "coordinates": [[[[0, 0], [10, 0], [10, 10], [0, 0]]], [[[20, 0], [30, 0], [20, 10], [20, 0]]]]}'
geometry = <MULTIPOLYGON (((0 0, 10 0, 10 10, 0 0)), ((20 0, 30 0, 20 10, 20 0)))>

    @pytest.mark.parametrize('geojson,geometry', [
        [ '''{"type": "Polygon", "coordinates": [[[0, 0], [10, 0], [10, 10], [0, 0]]]}''',
            shapely.geometry.Polygon([[0, 0], [10, 0], [10, 10], [0, 0]]), ],
        [ '''{"type": "MultiPolygon", "coordinates": [[[[0, 0], [10, 0], [10, 10], [0, 0]]], [[[20, 0], [30, 0], [20, 10], [20, 0]]]]}''',
            shapely.geometry.Polygon([[0, 0], [10, 0], [10, 10], [0, 0]]).union(shapely.geometry.Polygon([[20, 0], [30, 0], [20, 10], [20, 0]])), ],
        [ '''{"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[0, 0], [10, 0], [10, 10], [0, 0]]]}}''',
            shapely.geometry.Polygon([[0, 0], [10, 0], [10, 10], [0, 0]]), ],
        [ '''{"type": "FeatureCollection", "features": [{"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[0, 0], [10, 0], [10, 10], [0, 0]]]}}]}''',
            shapely.geometry.Polygon([[0, 0], [10, 0], [10, 10], [0, 0]]), ],
    ])
    def test_geojson(self, geojson, geometry):
        with TempFile() as fname:
            with open(fname, 'w') as f:
                f.write(geojson)
>           polygon = load_geojson(fname)
```
```
____________________ TestTransform.test_multipolygon_transf ____________________

self = <mapproxy.test.unit.test_geom.TestTransform object at 0x7fc1d8d7a860>

    def test_multipolygon_transf(self):
        p1 = shapely.geometry.Polygon([(0, 0), (10, 0), (10, 10), (0, 10)])
        p2 = shapely.geometry.Polygon([(20, 20), (30, 20), (30, 30), (20, 30)])
        mp1 = shapely.geometry.MultiPolygon([p1, p2])
    
>       mp2 = transform_geometry(SRS(4326), SRS(900913), mp1)

mapproxy/test/unit/test_geom.py:191: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
mapproxy/util/geom.py:222: in transform_geometry
    result = transform_multipolygon(transf, geometry)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

transf = functools.partial(<function transform_xy at 0x7fc1da670d30>, SRS('EPSG:4326'), SRS('EPSG:900913'))
multipolygon = <MULTIPOLYGON (((0 0, 10 0, 10 10, 0 10, 0 0)), ((20 20, 30 20, 30 30, 20 30...>

    def transform_multipolygon(transf, multipolygon):
        transformed_polygons = []
>       for polygon in multipolygon:
E       TypeError: 'MultiPolygon' object is not iterable

mapproxy/util/geom.py:237: TypeError
```

## Expected Behavior
No test failures

## Actual Behavior
Test failures.

## Steps to Reproduce
1. Run mapproxy test suite with shapely >= 2.0

## Context
Evaluating the impact of moving the python-shapely Debian package from experimental to unstable before the freeze in February.

## Your Environment

* Version used: 1.15.1
* Environment name and version: Python 3.10.8 with Shapely 2.0rc2
* Server type and version: N/A
* Operating System and version: Debian unstable with python3-shapely from experimental

### PR DESCRIPTION
**Pull request by bnavigator**
Fixes #611 , supersedes #709 

Shapely 2 does not allow iterating over `MultiPolygon` directly: https://shapely.readthedocs.io/en/stable/migration.html

### CODE REVIEW

**Comment by bnavigator** [comment]
Bumping networkx due to numpy.int error as well (Shapely 2 requires numpy). Needs to bump moto, cfn-lint as well.

Has anybody told you yet how annoying it is to pin to old incompatible versions?

**Comment by landryb** [comment]
Fwiw i'm not sure this is enough to fix runtime, running mapproxy-seed 1.15.1 with shapely 1.8.5 (versions available on debian bookworm) also complains about the use of `asShape()`:
```
/usr/lib/python3/dist-packages/mapproxy/util/geom.py:147: ShapelyDeprecationWarning: The proxy geometries (through the 'asShape()', 'asPolygon()' or 'PolygonAdapter()' constructors) are deprecated and will be removed in Shapely 2.0. Use the 'shape()' function or the standard 'Polygon()' constructor instead.
  geom = shapely.geometry.asShape(geom)
/usr/lib/python3/dist-packages/mapproxy/util/geom.py:147: ShapelyDeprecationWarning: The proxy geometries (through the 'asShape()', 'asMultiPolygon()' or 'MultiPolygonAdapter()' constructors) are deprecated and will be removed in Shapely 2.0. Use the 'shape()' function or the standard 'MultiPolygon()' constructor instead.
  geom = shapely.geometry.asShape(geom)
/usr/lib/python3/dist-packages/mapproxy/util/geom.py:237: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  for polygon in multipolygon:
```

**Comment by bnavigator** [comment]
> /usr/lib/python3/dist-packages/mapproxy/util/geom.py:147: ShapelyDeprecationWarning: The proxy geometries (through the 'asShape()', 'asPolygon()' or 'PolygonAdapter()' constructors) are deprecated and will be removed in Shapely 2.0. Use the 'shape()' function or the standard 'Polygon()' constructor instead.
>   geom = shapely.geometry.asShape(geom)
> /usr/lib/python3/dist-packages/mapproxy/util/geom.py:147: ShapelyDeprecationWarning: The proxy geometries (through the 'asShape()', 'asMultiPolygon()' or 'MultiPolygonAdapter()' constructors) are deprecated and will be removed in Shapely 2.0. Use the 'shape()' function or the standard 'MultiPolygon()' constructor instead.
>   geom = shapely.geometry.asShape(geom)

This has already been fixed in 1.16.0: https://github.com/mapproxy/mapproxy/commit/dd4fa8ba3f28e1ab5a4687e52d4cc963c4fe2adb

> /usr/lib/python3/dist-packages/mapproxy/util/geom.py:237: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
>   for polygon in multipolygon:

This is fixed in this very PR.

**Comment by landryb** [comment]
> > ```
> > /usr/lib/python3/dist-packages/mapproxy/util/geom.py:147: ShapelyDeprecationWarning: The proxy geometries (through the 'asShape()', 'asPolygon()' or 'PolygonAdapter()' constructors) are deprecated and will be removed in Shapely 2.0. Use the 'shape()' function or the standard 'Polygon()' constructor instead.
> >   geom = shapely.geometry.asShape(geom)
> > /usr/lib/python3/dist-packages/mapproxy/util/geom.py:147: ShapelyDeprecationWarning: The proxy geometries (through the 'asShape()', 'asMultiPolygon()' or 'MultiPolygonAdapter()' constructors) are deprecated and will be removed in Shapely 2.0. Use the 'shape()' function or the standard 'MultiPolygon()' constructor instead.
> >   geom = shapely.geometry.asShape(geom)
> > ```
> 
> This has already been fixed in 1.16.0: [dd4fa8b](https://github.com/mapproxy/mapproxy/commit/dd4fa8ba3f28e1ab5a4687e52d4cc963c4fe2adb)

oh great, hadnt look at git history on the file.. disregard my comment then :)

**Comment by weskamm** [comment]
Thanks for that!
