### ISSUE TITLE
Possible bug in MapProxy 1.15.0 and 1.15.1 related to SQLite caches

### ISSUE THREAD

**Issue by spechtx** [mapproxy/mapproxy#629]
## Context
Description:
When I try to run mapproxy-seed in MapProxy 1.15.0, I get the following error:

```Traceback (most recent call last):
  File "/home/USER/projects/development/mapproxy/.venv/bin/mapproxy-seed", line 8, in <module>
    sys.exit(main())
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/script.py", line 367, in main
    return SeedScript()()
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/script.py", line 224, in __call__
    seed_tasks = seed_conf.seeds(seed_names)
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/config.py", line 201, in seeds
    seed_conf = SeedConfiguration(seed_name, seed_conf, self)
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/config.py", line 282, in __init__
    ConfigurationBase.__init__(self, name, conf, seeding_conf)
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/config.py", line 229, in __init__
    self.caches = self._caches()
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/config.py", line 276, in _caches
    caches[cache_name] = self.seeding_conf.cache(cache_name)
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/config.py", line 171, in cache
    for tile_grid, extent, tile_mgr in self.mapproxy_conf.caches[cache_name].caches():
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/util/py.py", line 78, in wrapper
    cache[key] = func(self, *args, **kwargs)
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/config/loader.py", line 1481, in caches
    from mapproxy.cache.tile import TileManager
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/cache/tile.py", line 439
    <<<<<<< Updated upstream
    ^^
SyntaxError: invalid syntax
```

When I try to seed in 1.15.1 **after deleting the cache**, the first seeding runs without any problems. However, when I try to repeat the seeding, I get the following error:

```Traceback (most recent call last):
  File "/home/USER/projects/development/mapproxy/.venv/bin/mapproxy-seed", line 8, in <module>
    sys.exit(main())
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/script.py", line 367, in main
    return SeedScript()()
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/script.py", line 249, in __call__
    seed(seed_tasks, progress_logger=logger, dry_run=options.dry_run,
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/seeder.py", line 498, in seed
    seed_task(task, concurrency, dry_run, skip_geoms_for_last_levels, progress_logger,
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/seeder.py", line 531, in seed_task
    tile_walker.walk()
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/seeder.py", line 326, in walk
    self._walk(bbox, self.task.levels)
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/seeder.py", line 374, in _walk
    self._walk(sub_bbox, levels, current_level=current_level+1,
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/seeder.py", line 374, in _walk
    self._walk(sub_bbox, levels, current_level=current_level+1,
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/seeder.py", line 374, in _walk
    self._walk(sub_bbox, levels, current_level=current_level+1,
  [Previous line repeated 9 more times]
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/seeder.py", line 394, in _walk
    handle_tiles = [t for t in handle_tiles if
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/seed/seeder.py", line 396, in <listcomp>
    not self.tile_mgr.is_cached(t)]
  File "/home/USER/projects/development/mapproxy/.venv/lib/python3.10/site-packages/mapproxy/cache/tile.py", line 209, in is_cached
    self.cache.load_tile_metadata(tile)
TypeError: MBTilesLevelCache.load_tile_metadata() missing 1 required positional argument: 'dimensions'
```

In contrast, everything works fine in 1.14.0.

Steps to reproduce:

Install MapProxy 1.15.0 or 1.15.1.
Try to run mapproxy-seed with sqlite cache. The error described above occurs.
Delete the cache and run mapproxy-seed again. The first seeding runs successfully in 1.15.1.
Try to run mapproxy-seed again. The second seeding fails with the error described above.
Expected result:
Seeding should work without any errors.

Actual result:
Errors occur in 1.15.0 and 1.15.1, but not in 1.14.0.

Additional information:
The issue seems to be related to the SQLite caches. It's possible that there's a syntax error in the code for MapProxy 1.15.0, which causes the first error. The second error in 1.15.1 seems to be caused by a missing positional argument in the `MBTilesLevelCache.load

## Your Environment

* Version used: 
* Environment name and version: python 3.10.16 
* Operating System and version: Ubuntu Server 22.04 LTS

This issue from @https://github.com/tobias-brunner could be related:
refresh_before not working anymore
[https://github.com/mapproxy/mapproxy/issues/625](https://github.com/mapproxy/mapproxy/issues/625)

**Comment by weskamm** [comment]
fixed in the latest release 1.16.0
